name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.TOKEN_NPM}}" >> ~/.npmrc
      - run: echo "@verybigthings:registry=https://registry.npmjs.org" >> ~/.npmrc
      - run: npm i
      - run: npm run build-bundle
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_NPM}}
        continue-on-error: true
